### ISSUE TITLE
Reports the same channels couple of times and stops with an error

### ISSUE THREAD

**Issue by sivanmu** [deli841/tg_reporter#8]
Hi there! It worked and I could see, how the script opens and reports the same channel 3 times, but it breaks after that and I can see the  following error in the cmd prompt:
![channelreporter](https://user-images.githubusercontent.com/56482114/158613487-83b3d618-ecd3-453d-adee-f5aeed01b882.JPG)

I am using Windows 10, python version 3.8.4

**Comment by megger-cgfx** [comment]
Same thing here on two of my devices. It runs for about two minutes before erroring out unfortunately.

Device 1) Windows 10 with Python 3.8.12 (venv through Conda). This one has a RTX3070 and a Ryzen 7 3900X.

Device 2) WIndows 11 with Python 3.8.4 (not Conda). This one only has a Ryzen 5800H.

```
C:\Users\myuser\Downloads\tg_reporter-main>python main.py

DevTools listening on ws://127.0.0.1:3852/devtools/browser/66bd02e7-d134-4953-87ca-3b3484745724
Attempt: 0
Attempt: 1
[14600:10892:0316/153249.674:ERROR:device_event_log_impl.cc(214)] [15:32:49.674] USB: usb_service_win.cc:391 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
[14600:10892:0316/153249.675:ERROR:device_event_log_impl.cc(214)] [15:32:49.675] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[14600:10892:0316/153249.675:ERROR:device_event_log_impl.cc(214)] [15:32:49.675] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
Enter your phone number, starting with a '+': +4917657778959
Please enter code to log into your account (5 digits): 10745
Attempt: 0
code_input= ['', '', '']
Attempt: 1
code_input= ['', '', '']
Attempt: 2
code_input= ['', '', '']
Attempt: 3
code_input= ['', '', '', '']
Attempt: 4
code_input= ['']
Attempt: 5
code_input= ['']
Attempt: 6
code_input= ['']


Attempting to block: https://t.me/Doninside
    Attempt: 0
    Attempt: 1
    Attempt: 2
  Can't handle this channel
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    back_button.click()
  File "C:\Users\myuser\.conda\envs\tg-rep-env\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\myuser\.conda\envs\tg-rep-env\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\myuser\.conda\envs\tg-rep-env\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\myuser\.conda\envs\tg-rep-env\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=99.0.4844.51)
Stacktrace:
Backtrace:
        Ordinal0 [0x00679943+2595139]
        Ordinal0 [0x0060C9F1+2148849]
        Ordinal0 [0x005043F0+1065968]
        Ordinal0 [0x00531F17+1253143]
        Ordinal0 [0x00527AB3+1211059]
        Ordinal0 [0x0054B9EC+1358316]
        Ordinal0 [0x00527474+1209460]
        Ordinal0 [0x0054BC04+1358852]
        Ordinal0 [0x0055BAF2+1424114]
        Ordinal0 [0x0054B806+1357830]
        Ordinal0 [0x00526086+1204358]
        Ordinal0 [0x00526F96+1208214]
        GetHandleVerifier [0x0081B232+1658114]
        GetHandleVerifier [0x008D312C+2411516]
        GetHandleVerifier [0x0070F261+560433]
        GetHandleVerifier [0x0070E366+556598]
        Ordinal0 [0x0061286B+2173035]
        Ordinal0 [0x006175F8+2192888]
        Ordinal0 [0x006176E5+2193125]
        Ordinal0 [0x006211FC+2232828]
        BaseThreadInitThunk [0x76326739+25]
        RtlGetFullPathName_UEx [0x773B8E7F+1215]
        RtlGetFullPathName_UEx [0x773B8E4D+1165]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 153, in <module>
    back_button.click()
  File "C:\Users\myuser\.conda\envs\tg-rep-env\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\myuser\.conda\envs\tg-rep-env\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\myuser\.conda\envs\tg-rep-env\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\myuser\.conda\envs\tg-rep-env\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=99.0.4844.51)
Stacktrace:
Backtrace:
        Ordinal0 [0x00679943+2595139]
        Ordinal0 [0x0060C9F1+2148849]
        Ordinal0 [0x005043F0+1065968]
        Ordinal0 [0x00531F17+1253143]
        Ordinal0 [0x00527AB3+1211059]
        Ordinal0 [0x0054B9EC+1358316]
        Ordinal0 [0x00527474+1209460]
        Ordinal0 [0x0054BC04+1358852]
        Ordinal0 [0x0055BAF2+1424114]
        Ordinal0 [0x0054B806+1357830]
        Ordinal0 [0x00526086+1204358]
        Ordinal0 [0x00526F96+1208214]
        GetHandleVerifier [0x0081B232+1658114]
        GetHandleVerifier [0x008D312C+2411516]
        GetHandleVerifier [0x0070F261+560433]
        GetHandleVerifier [0x0070E366+556598]
        Ordinal0 [0x0061286B+2173035]
        Ordinal0 [0x006175F8+2192888]
        Ordinal0 [0x006176E5+2193125]
        Ordinal0 [0x006211FC+2232828]
        BaseThreadInitThunk [0x76326739+25]
        RtlGetFullPathName_UEx [0x773B8E7F+1215]
        RtlGetFullPathName_UEx [0x773B8E4D+1165]


(tg-rep-env) C:\Users\myuser\Downloads\tg_reporter-main>[20460:19704:0316/153447.263:ERROR:dxva_video_decode_accelerator_win.cc(1461)] DXVAVDA fatal error: could not LoadLibrary: mf.dll: The specified module could not be found. (0x7E)
[20460:19704:0316/153447.263:ERROR:dxva_video_decode_accelerator_win.cc(1461)] DXVAVDA fatal error: could not LoadLibrary: mfplat.dll: The specified module could not be found. (0x7E)
[20460:19704:0316/153447.265:ERROR:dxva_video_decode_accelerator_win.cc(1461)] DXVAVDA fatal error: could not LoadLibrary: msmpeg2vdec.dll: The specified module could not be found. (0x7E)
[20460:19704:0316/153447.265:ERROR:dxva_video_decode_accelerator_win.cc(1469)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: The specified module could not be found. (0x7E)
[20460:19704:0316/153447.267:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled, ANGLE is

```
